version: '3'

services:
  app:
    container_name: app
    restart: always
    build: ./ranzcr_clip
    ports:
      - "8501:8501"
    command: streamlit run app/app.py
    environment:
      - PYTHONPATH=.

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
