# Black configuration
[tool.black]
line-length = 119
skip-string-normalization = true
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | archived_checkpoints
  | buck-out
  | build
  | checkpoints
  | data
  | dist
  | logs
)/
'''
